# Generated by Django 4.2.2 on 2023-06-21 04:33

import appointments.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=appointments.models.Status),
        ),
    ]
